# Packages
```{r}
library(kernlab)
library(e1071)
library(tidyverse)
library(ggthemes)
library(gridExtra)
library(caret)
library(tm)

```

# Step 1: Load the data
```{r}
# Loading the airquality data and saving it in a new df
my_airquality <- airquality

# Checking the summary of the df
summary(my_airquality)
# There are NAs in $Ozone and $Solar.R

# Imputing the means for NA observations
my_airquality$Ozone[is.na(my_airquality$Ozone)==T] <- mean(my_airquality$Ozone, na.rm=T)
my_airquality$Solar.R[is.na(my_airquality$Solar.R)==T] <- mean(my_airquality$Solar.R, na.rm=T)

# Now that all NAs have been imputed, the sum of NAs should be 0
sum(is.na(my_airquality)) # 0

```

# Step 2: Create train and test data sets
```{r}
# splitting the data into 2/3 training data and 1/3 testing data
random_indicies <- sample(1:nrow(my_airquality))
cutoff_point <- floor(2 * nrow(my_airquality) / 3)

my_airquality_TRAIN <- my_airquality[random_indicies[1:cutoff_point], ]
my_airquality_TEST <- my_airquality[random_indicies[(cutoff_point + 1):nrow(my_airquality)], ]

```

# Step 3: Build a model using KSVM and visualize the results
```{r}
# Build a model using the ksvm function, trying to predict Ozone
ksvm_1 <- ksvm(Ozone ~ ., data=my_airquality_TRAIN)
ksvm_1

# Test the model on the testing set and compute the RMSE
ksvm_1_predictions <- predict(ksvm_1, my_airquality_TEST, type="votes")
my_airquality_TEST$ksvm_1_predictions <- ksvm_1_predictions[ , 1]
ksvm_1_RMSE <- sqrt(mean((my_airquality_TEST$Ozone - my_airquality_TEST$ksvm_1_predictions)^2))

# Plot the results
my_airquality_TEST <- my_airquality_TEST %>% 
  mutate(error = abs(Ozone - ksvm_1_predictions))

ggplot(my_airquality_TEST, mapping=aes(x=Temp, y=Wind, color=error, size=error)) +
  geom_point() +
  xlab("Temperature") +
  ylab("Wind Speed") +
  ggtitle("KSVM") +
  theme_tufte()

# Compute models and plot the results for 'svm' and 'lm'
# -- SVM
svm_1 <- svm(Ozone ~ ., data=my_airquality_TRAIN)
svm_1

my_airquality_TEST$svm_1_predictions <- predict(svm_1, my_airquality_TEST, type="votes")
svm_1_RMSE <- sqrt(mean((my_airquality_TEST$Ozone - my_airquality_TEST$svm_1_predictions)^2))

my_airquality_TEST <- my_airquality_TEST %>% 
  mutate(svm_error = abs(Ozone - svm_1_predictions))

ggplot(my_airquality_TEST, mapping=aes(x=Temp, y=Wind, color=svm_error, size=svm_error)) +
  geom_point() +
  xlab("Temperature") +
  ylab("Wind Speed") +
  ggtitle("SVM") +
  theme_tufte()

# --LM
lm_1 <- lm(Ozone ~ ., data=my_airquality_TRAIN)
lm_1

my_airquality_TEST$lm_1_predictions <- predict(lm_1, my_airquality_TEST)
lm_1_RMSE <- sqrt(mean((my_airquality_TEST$Ozone - my_airquality_TEST$lm_1_predictions)^2))

my_airquality_TEST <- my_airquality_TEST %>% 
  mutate(lm_error = abs(Ozone - lm_1_predictions))

ggplot(my_airquality_TEST, mapping=aes(x=Temp, y=Wind, color=lm_error, size=lm_error)) +
  geom_point() +
  xlab("Temperature") +
  ylab("Wind Speed") +
  ggtitle("Linear Model") +
  theme_tufte()

```

# Step 4: Create a `goodOzone` variable
```{r}
# If individual ozone value is less than mean assign 0 to goodOzone, if individual value is equal to or greater than the mean assign 1 to goodOzone
mean_ozone <- mean(my_airquality$Ozone)

# adding the variable to the TRAINING data set and dropping Ozone
my_airquality_TRAIN$goodOzone <- ifelse(my_airquality_TRAIN$Ozone < mean_ozone, 0, 1)
my_airquality_TRAIN$goodOzone <- as.factor(my_airquality_TRAIN$goodOzone)
my_airquality_TRAIN$Ozone <- NULL

# adding the variable to the TESTING data set and dropping Ozone
my_airquality_TEST$goodOzone <- ifelse(my_airquality_TEST$Ozone < mean_ozone, 0, 1)
my_airquality_TEST$goodOzone <- as.factor(my_airquality_TEST$goodOzone)
my_airquality_TEST$Ozone <- NULL

```

# Step 5: See if we can do a better job prediction 'good' and 'bad' days
```{r}
# Build a model using the ksvm function, trying to predict goodOzone
ksvm_2 <- ksvm(goodOzone ~ ., data=my_airquality_TRAIN)
ksvm_2

# Test the model on the testing set and compute the percentage of goodOzone that was correctly predicted
my_airquality_TEST$ksvm_2_predictions <- predict(ksvm_2, my_airquality_TEST)

ksvm_2_accuracy <- sum(my_airquality_TEST$ksvm_2_predictions == my_airquality_TEST$goodOzone)/nrow(my_airquality_TEST)

# Plot the results
my_airquality_TEST <- my_airquality_TEST %>% 
  mutate(ksvm_2_correct_prediction = as.factor(ifelse(ksvm_2_predictions == goodOzone, "correct", "wrong")))

ggplot(my_airquality_TEST, mapping=aes(x=Temp, y=Wind, shape=ksvm_2_predictions, color=goodOzone, size=ksvm_2_correct_prediction)) +
  geom_point() +
  xlab("Temperature") +
  ylab("Wind Speed") +
  ggtitle("KSVM - Good/Bad Ozone") +
  theme_tufte()

# Compute the models and plot the results for 'svm' and 'nb'
# -- SVM
svm_2 <- svm(goodOzone ~ ., data=my_airquality_TRAIN)
svm_2

# Test the model on the testing set and compute the percentage of goodOzone that was correctly predicted
my_airquality_TEST$svm_2_predictions <- predict(svm_2, my_airquality_TEST)

svm_2_accuracy <- sum(my_airquality_TEST$svm_2_predictions == my_airquality_TEST$goodOzone)/nrow(my_airquality_TEST)

# Plot the results
my_airquality_TEST <- my_airquality_TEST %>% 
  mutate(svm_2_correct_prediction = as.factor(ifelse(svm_2_predictions == goodOzone, "correct", "wrong")))

ggplot(my_airquality_TEST, mapping=aes(x=Temp, y=Wind, shape=svm_2_predictions, color=goodOzone, size=svm_2_correct_prediction)) +
  geom_point() +
  xlab("Temperature") +
  ylab("Wind Speed") +
  ggtitle("SVM - Good/Bad Ozone") +
  theme_tufte()

# -- Naive bayes
nb_1 <- naiveBayes(goodOzone ~ ., data=my_airquality_TRAIN)
nb_1

# Test the model on the testing set and compute the percentage of goodOzone that was correctly predicted
my_airquality_TEST$nb_1_predictions <- predict(nb_1, my_airquality_TEST)

nb_1_accuracy <- sum(my_airquality_TEST$nb_1_predictions == my_airquality_TEST$goodOzone)/nrow(my_airquality_TEST)

# Plot the results
my_airquality_TEST <- my_airquality_TEST %>% 
  mutate(nb_1_correct_prediction = as.factor(ifelse(nb_1_predictions == goodOzone, "correct", "wrong")))

ggplot(my_airquality_TEST, mapping=aes(x=Temp, y=Wind, shape=nb_1_predictions, color=goodOzone, size=nb_1_correct_prediction)) +
  geom_point() +
  xlab("Temperature") +
  ylab("Wind Speed") +
  ggtitle("Naive Bayes - Good/Bad Ozone") +
  theme_tufte()

```

# Step 6: Which are the best models for this data?
```{r}
# -- Regression models
# The regression models should be based on their RMSE
# The best regression model would be the one which has the lowest RMSE value
print("The RMSE for the KSVM regression model is: " + as.String(round(ksvm_1_RMSE, 4)))
print("The RMSE for the SVM regression model is: " + as.String(round(svm_1_RMSE, 4)))
print("The RMSE for the linear regression model is: " + as.String(round(lm_1_RMSE, 4)))

# -- Classification models
# The classification models should be based on their accuracy
# The best classification model would be the one which has the highest accuracy value
print("The accuracy for the KSVM classification model is: " + as.String(round(ksvm_2_accuracy * 100, 4)) + "%")
print("The accuracy for the SVM classification model is: " + as.String(round(svm_2_accuracy * 100, 4)) + "%")
print("The accuracy for the Naive Bayes classification model is: " + as.String(round(nb_1_accuracy * 100, 4)) + "%")


```
